apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-processor
spec:
  replicas: 2
  selector:
    matchLabels:
      app: processor
  template:
    metadata:
      labels:
        app: processor
    spec:
      containers:
      - name: processor
        imagePullPolicy: Never
        image: payment-processor:1.0
        ports:
        - containerPort: 8080